### ISSUE TITLE
`scripts/automatic_lang_annotator_mp.py` appears to be broken

### ISSUE THREAD

**Issue by ezhang7423** [mees/calvin#24]
The configuration file that this script uses, `lang_ann.yml`, does not appear to have two required keys: `rollout_sentences` and `annotations`. To replicate this, one can simply try running the script.

**Comment by ezhang7423** [comment]
Command: 
`python3 hulc/utils/automatic_lang_annotator_mp.py datamodule.root_data_dir=/data2/eddie/calvin/task_D_D datamodule/datasets=vision_lang +rollout_sentences=new_playtable`
Output:
```
[2022-08-04 11:03:46,129][hulc.datasets.base_dataset][INFO] - loading dataset at /data2/eddie/calvin/task_D_D/training
[2022-08-04 11:03:46,130][hulc.datasets.base_dataset][INFO] - finished loading dataset
[2022-08-04 11:03:46,131][hulc.datasets.disk_dataset][INFO] - Found "ep_start_end_ids.npy" with 31 episodes.
[2022-08-04 11:03:46,215][hulc.datasets.base_dataset][INFO] - loading dataset at /data2/eddie/calvin/task_D_D/validation
[2022-08-04 11:03:46,215][hulc.datasets.base_dataset][INFO] - finished loading dataset
[2022-08-04 11:03:46,216][hulc.datasets.disk_dataset][INFO] - Found "ep_start_end_ids.npy" with 4 episodes.
[2022-08-04 11:03:46,240][hulc.datasets.base_dataset][INFO] - loading dataset at /data2/eddie/calvin/task_D_D/training
[2022-08-04 11:03:46,241][hulc.datasets.base_dataset][INFO] - finished loading dataset
trying to load lang data from:  /data2/eddie/calvin/task_D_D/training/lang_annotations/auto_lang_ann.npy
[2022-08-04 11:03:46,326][hulc.datasets.base_dataset][INFO] - loading dataset at /data2/eddie/calvin/task_D_D/validation
[2022-08-04 11:03:46,326][hulc.datasets.base_dataset][INFO] - finished loading dataset
trying to load lang data from:  /data2/eddie/calvin/task_D_D/validation/lang_annotations/auto_lang_ann.npy
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7]
Missing logger folder: /home/eddie/git/lad_/runs/2022-08-04/11-03-40_datamodule/datasets=vision_lang/lightning_logs
/home/eddie/.miniconda3/envs/lad/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:132: UserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 64 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
[2022-08-04 11:03:53,919][hulc.wrappers.hulc_wrapper][INFO] - EGL_DEVICE_ID 0 <==> CUDA_DEVICE_ID 0
argv[0]=--width=None
argv[1]=--height=None
[2022-08-04 11:03:54,054][calvin_env.envs.play_table_env][INFO] - Loading EGL plugin (may segfault on misconfigured systems)...
[2022-08-04 11:03:54,055][calvin_env.envs.play_table_env][INFO] - Successfully loaded egl plugin
[2022-08-04 11:03:54,055][calvin_env.envs.play_table_env][INFO] - Connected to server with id: 1
[2022-08-04 11:03:54,057][calvin_env.envs.play_table_env][INFO] - Connected to server with id: 1
[2022-08-04 11:03:54,066][calvin_env.robot.robot][INFO] - Loading robot
[2022-08-04 11:03:54,080][calvin_env.envs.play_table_env][INFO] - Resetting simulation
[2022-08-04 11:03:54,082][calvin_env.envs.play_table_env][INFO] - Setting gravity
[2022-08-04 11:03:54,752][calvin_env.envs.play_table_env][INFO] - Using calvin_env with commit af69b2ac62cdf125297b757ebbdbbed339368ec4.
/home/eddie/.miniconda3/envs/lad/lib/python3.8/site-packages/gym/core.py:329: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
[2022-08-04 11:03:54,753][hulc.wrappers.hulc_wrapper][INFO] - Initialized PlayTableEnv for device cuda:0
[2022-08-04 11:03:54,757][hulc.wrappers.hulc_wrapper][WARNING] - Environment variable EGL_VISIBLE_DEVICES is already set. Is this intended?
[2022-08-04 11:03:55,881][hulc.wrappers.hulc_wrapper][INFO] - EGL_DEVICE_ID 0 <==> CUDA_DEVICE_ID 0
argv[0]=--width=None
argv[1]=--height=None
[2022-08-04 11:03:56,008][calvin_env.envs.play_table_env][INFO] - Loading EGL plugin (may segfault on misconfigured systems)...
[2022-08-04 11:03:56,009][calvin_env.envs.play_table_env][INFO] - Successfully loaded egl plugin
[2022-08-04 11:03:56,009][calvin_env.envs.play_table_env][INFO] - Connected to server with id: 2
[2022-08-04 11:03:56,011][calvin_env.envs.play_table_env][INFO] - Connected to server with id: 2
[2022-08-04 11:03:56,018][calvin_env.robot.robot][INFO] - Loading robot
[2022-08-04 11:03:56,030][calvin_env.envs.play_table_env][INFO] - Resetting simulation
[2022-08-04 11:03:56,032][calvin_env.envs.play_table_env][INFO] - Setting gravity
[2022-08-04 11:03:56,483][calvin_env.envs.play_table_env][INFO] - Using calvin_env with commit af69b2ac62cdf125297b757ebbdbbed339368ec4.
/home/eddie/.miniconda3/envs/lad/lib/python3.8/site-packages/gym/core.py:329: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
[2022-08-04 11:03:56,484][hulc.wrappers.hulc_wrapper][INFO] - Initialized PlayTableEnv for device cuda:0
[2022-08-04 11:03:56,888][sentence_transformers.SentenceTransformer][INFO] - Load pretrained SentenceTransformer: paraphrase-MiniLM-L3-v2
[2022-08-04 11:03:57,283][sentence_transformers.SentenceTransformer][INFO] - Use pytorch device: cuda
Batches: 100%|██████████████████████████████████████████| 1/1 [00:00<00:00, 20.74it/s]
Batches: 100%|██████████████████████████████████████████| 1/1 [00:00<00:00, 92.58it/s]
Batches: 100%|██████████████████████████████████████████| 1/1 [00:00<00:00, 86.62it/s]
Batches: 100%|██████████████████████████████████████████| 1/1 [00:00<00:00, 92.09it/s]
Batches: 100%|██████████████████████████████████████████| 1/1 [00:00<00:00, 66.53it/s]
Batches: 100%|██████████████████████████████████████████| 1/1 [00:00<00:00, 74.24it/s]
Batches: 100%|██████████████████████████████████████████| 1/1 [00:00<00:00, 94.94it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 244.28it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 245.74it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 225.39it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 186.65it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 118.89it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 148.47it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 159.07it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 157.80it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 154.21it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 130.36it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 151.82it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 173.91it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 108.95it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 125.15it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 106.25it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 189.05it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 195.46it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 114.76it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 149.77it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 154.32it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 193.11it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 155.28it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 180.41it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 246.39it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 206.04it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 159.53it/s]
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 160.39it/s]
[2022-08-04 11:03:57,794][__main__][INFO] - Done saving val language embeddings for Rollouts !
Error executing job with overrides: ['datamodule.root_data_dir=/data2/eddie/calvin/task_D_D', 'datamodule/datasets=vision_lang']
Traceback (most recent call last):
  File "hulc/utils/automatic_lang_annotator_mp.py", line 371, in main
  File "/home/eddie/.miniconda3/envs/lad/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "/home/eddie/.miniconda3/envs/lad/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/eddie/.miniconda3/envs/lad/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/eddie/.miniconda3/envs/lad/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/home/eddie/.miniconda3/envs/lad/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/home/eddie/.miniconda3/envs/lad/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/home/eddie/.miniconda3/envs/lad/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in run_stage
    return self._run_train()
  File "/home/eddie/.miniconda3/envs/lad/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1319, in _run_train
    self.fit_loop.run()
  File "/home/eddie/.miniconda3/envs/lad/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 140, in run
    self.on_run_start(*args, **kwargs)
  File "/home/eddie/.miniconda3/envs/lad/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 200, in on_run_start
    self.trainer.call_hook("on_train_start")
  File "/home/eddie/.miniconda3/envs/lad/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1495, in call_hook
    callback_fx(*args, **kwargs)
  File "/home/eddie/.miniconda3/envs/lad/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py", line 138, in on_train_start
    callback.on_train_start(self, self.lightning_module)
  File "hulc/utils/automatic_lang_annotator_mp.py", line 135, in on_train_start
    outputs: Any,
  File "hulc/utils/automatic_lang_annotator_mp.py", line 125, in init_vars
    self.init_vars(trainer, pl_module)
AttributeError: 'NoneType' object has no attribute 'keys'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
disconnecting id 1 from server
disconnecting id 2 from server
Destroy EGL OpenGL window.
```

**Comment by mees** [comment]
Thanks for your report, can you run the command with `datamodule/datasets=vision_only` please? Other parameters that you can set are the window sizes to consider and what percentage of the data should get labeled with language. You might want to check those defaults, in case you want to change them for your application.

**Comment by lukashermann** [comment]
You are right, the script was indeed broken. I commited a fix, can you try if it works now? I also added some keys to the config, so now it should be enough to run it as 
`python3 hulc/utils/automatic_lang_annotator_mp.py datamodule.root_data_dir=/data2/eddie/calvin/task_D_D`

**Comment by ezhang7423** [comment]
Thank you so much! The new commit works for me.
